name: Middleman deploy on push
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install bundler
        run: gem install bundler:2.1.4
      - name: Bundle install
        run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
      - name: npm install packages
        run: |
          npm install
      - name: Build site
        run: bundle exec middleman build
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
